# Generated by Django 3.0.5 on 2020-11-20 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('first_name', models.CharField(default='first_name', max_length=100)),
                ('last_name', models.CharField(default='last_name', max_length=100)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('phone_number', models.CharField(default='phone', max_length=10)),
                ('profile_pic', models.ImageField(default='no_image.png', upload_to='user_profile_pics/')),
                ('dob', models.DateField(default=datetime.datetime.today)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
