# Generated by Django 3.0.4 on 2020-10-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='guidedata',
            name='place',
            field=models.ManyToManyField(to='guide.Place'),
        ),
    ]
