# Generated by Django 3.0.5 on 2020-10-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monuments', '0001_initial'),
        ('guide', '0002_auto_20201028_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidedata',
            name='place',
            field=models.ManyToManyField(to='monuments.Monument'),
        ),
    ]
