# Generated by Django 3.0.4 on 2020-10-28 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_auto_20201028_1709'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
