# Generated by Django 3.0.5 on 2020-10-31 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Monument',
            fields=[
                ('monument_id', models.AutoField(primary_key=True, serialize=False)),
                ('monument_name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('basic_info', models.TextField()),
                ('pin_code', models.CharField(max_length=6)),
                ('city', models.ManyToManyField(to='monuments.City')),
            ],
        ),
        migrations.CreateModel(
            name='MonumentInfo',
            fields=[
                ('monument_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('monument_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monuments.Monument')),
            ],
        ),
    ]
