# Generated by Django 3.0.5 on 2020-11-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monuments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monument',
            name='city',
        ),
        migrations.RemoveField(
            model_name='monument',
            name='place',
        ),
        migrations.AddField(
            model_name='city',
            name='city_info',
            field=models.TextField(default='city info'),
        ),
        migrations.AddField(
            model_name='city',
            name='imageURL',
            field=models.TextField(default='https://img.freepik.com/free-vector/cityscape-cartoon-background-panorama-modern-city-with-high-skyscrapers-park-downtown_1441-1982.jpg?size=626&ext=jpg'),
        ),
        migrations.AddField(
            model_name='city',
            name='monuments',
            field=models.ManyToManyField(to='monuments.Monument'),
        ),
        migrations.AddField(
            model_name='monument',
            name='imageURL',
            field=models.TextField(default='https://img.freepik.com/free-vector/cityscape-cartoon-background-panorama-modern-city-with-high-skyscrapers-park-downtown_1441-1982.jpg?size=626&ext=jpg'),
        ),
        migrations.AddField(
            model_name='monumentinfo',
            name='imageURL',
            field=models.TextField(default='https://img.freepik.com/free-vector/cityscape-cartoon-background-panorama-modern-city-with-high-skyscrapers-park-downtown_1441-1982.jpg?size=626&ext=jpg'),
        ),
    ]
