# Generated by Django 3.0.5 on 2020-11-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monuments', '0002_auto_20201122_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_info',
            field=models.TextField(default='city info'),
        ),
        migrations.AddField(
            model_name='monumentinfo',
            name='imageURL',
            field=models.TextField(default='https://img.freepik.com/free-vector/cityscape-cartoon-background-panorama-modern-city-with-high-skyscrapers-park-downtown_1441-1982.jpg?size=626&ext=jpg'),
        ),
    ]
