# Generated by Django 3.0.4 on 2020-10-24 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='GuideData',
            fields=[
                ('guide_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('profile_pic', models.ImageField(default='no_image.png', upload_to='guide_profile_pics/')),
                ('dob', models.DateField(default=datetime.datetime.today)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Monument',
            fields=[
                ('monument_id', models.AutoField(primary_key=True, serialize=False)),
                ('monument_name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('basic_info', models.TextField()),
                ('pin_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('profile_pic', models.ImageField(default='no_image.png', upload_to='user_profile_pics/')),
                ('dob', models.DateField(default=datetime.datetime.today)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
