# Generated by Django 3.0.5 on 2020-10-31 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='book_id',
            new_name='booking_id',
        ),
    ]
