# Generated by Django 3.0.4 on 2020-10-24 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0002_booking_monumentinfo_payment_userhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserHistory',
        ),
    ]
