# Generated by Django 3.0.4 on 2020-10-24 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0003_delete_userhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='mode_of_payment',
            field=models.CharField(choices=[('1', 'Debit/Credit card'), ('2', 'UPI'), ('3', 'Cash'), ('4', 'Net banking')], default='2', max_length=1),
        ),
        migrations.CreateModel(
            name='UserTravelHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_of_travel', models.IntegerField(choices=[(1, 'Bus'), (2, 'Flight'), (3, 'Train'), (4, 'Cab'), (5, 'Ship')], default=1)),
                ('travel_amount', models.IntegerField()),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ut_user_email', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserStayHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodge', models.CharField(max_length=100)),
                ('stay_amount', models.IntegerField()),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='us_user_email', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFoodHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.CharField(max_length=100)),
                ('food_amount', models.IntegerField()),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uf_user_email', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
