# Generated by Django 3.0.4 on 2020-10-24 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0004_auto_20201024_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_of_payment', models.CharField(choices=[('1', 'Debit/Credit card'), ('2', 'UPI'), ('3', 'Cash'), ('4', 'Net banking')], default='2', max_length=1)),
                ('food_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tourism.UserFoodHistory')),
                ('stay_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tourism.UserStayHistory')),
                ('timestamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_timestamp', to='Tourism.Booking')),
                ('travel_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tourism.UserTravelHistory')),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_user_email', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
