# Generated by Django 3.0.4 on 2020-10-24 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0005_userhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhistory',
            name='food_history',
        ),
        migrations.RemoveField(
            model_name='userhistory',
            name='stay_history',
        ),
        migrations.RemoveField(
            model_name='userhistory',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='userhistory',
            name='travel_history',
        ),
        migrations.RemoveField(
            model_name='userhistory',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='userstayhistory',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='usertravelhistory',
            name='user_email',
        ),
        migrations.DeleteModel(
            name='UserFoodHistory',
        ),
        migrations.DeleteModel(
            name='UserHistory',
        ),
        migrations.DeleteModel(
            name='UserStayHistory',
        ),
        migrations.DeleteModel(
            name='UserTravelHistory',
        ),
    ]
