# Generated by Django 3.0.4 on 2020-10-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0007_userhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
